onlinetest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('testsystem.urls')),
]

testsystem/urls.py
from django.urls import path

from . import views

app_name = 'testsystem'
urlpatterns = [
    path('', views.index),
    path('index/', views.index,name='index'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('<int:paper_id>/', views.paper, name='paper'),
    path('<int:paper_id>/cal/', views.cal_score, name='calculate'),
    path('forgetpwd/',views.forgetpwd,name='forgetpwd'),
    path('download/',views.download,name='download')
]

testsystem/models.py
from django.db import models
from django.conf import settings


# Create your models here.
IDENTITIES = (
    ('student','学生'),
    ('teacher','教师'),
)

SYMBOLS = (
    ('A','A'),
    ('B','B'),
    ('C','C'),
    ('D','D'),
    ('E','E'),
    ('F','F'),
)

class User(models.Model):

    gender = (
        ('male', "男"),
        ('female', "女"),
    )

    name = models.CharField('姓名',max_length=128)
    idcard = models.CharField('学号',max_length=128,unique=True)
    password = models.CharField('密码',max_length=256)
    email = models.EmailField('邮箱',unique=True)
    sex = models.CharField('性别',max_length=32, choices=gender, default="男")
    c_time = models.DateTimeField('注册时间', auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-c_time"]
        verbose_name = "用户"
        verbose_name_plural = "用户"

class Paper(models.Model):
    paper_text = models.CharField('试卷标题', max_length=30)
    pub_date = models.DateTimeField('发布日期', auto_now_add=True)
    time = models.TimeField("限时")

    def __str__(self):
        return self.paper_text
    
    class Meta:
        verbose_name = '试卷'
        verbose_name_plural = verbose_name

class SC_question(models.Model):
    SC_text = models.CharField('单选题内容', max_length=200)
    SC_solution = models.CharField('单选题答案', max_length=1, choices=SYMBOLS)
    value = models.DecimalField('分值', max_digits=4,decimal_places=1)
    paper = models.ForeignKey(Paper, on_delete=models.CASCADE)

    def __str__(self):
        return "sc_question{}".format(self.id)

    class Meta:
        verbose_name = '单选题'
        verbose_name_plural = verbose_name

class MC_question(models.Model):
    MC_text = models.CharField('多选题内容', max_length=200)
    MC_solution = models.CharField('多选题答案', max_length=6)
    value = models.DecimalField('分值', max_digits=4,decimal_places=1)
    paper = models.ForeignKey(Paper, on_delete=models.CASCADE)

    def __str__(self):
        return "mc_question{}".format(self.id)

    class Meta:
        verbose_name = '多选题'
        verbose_name_plural = verbose_name

class Blank_question(models.Model):
    blank_text = models.CharField('填空题内容', max_length=200)
    blank_solution = models.CharField('填空题答案', max_length=20)
    value = models.DecimalField('分值', max_digits=4,decimal_places=1)
    paper = models.ForeignKey(Paper, on_delete=models.CASCADE)

    def __str__(self):
        return "blank_question{}".format(self.id)

    class Meta:
        verbose_name = '填空题'
        verbose_name_plural = verbose_name

class SC_choice(models.Model):
    choice_symbol = models.CharField('选项符号', max_length=1, choices=SYMBOLS)
    choice_text = models.CharField('选项内容', max_length=200)
    question = models.ForeignKey(SC_question, on_delete=models.CASCADE)
    paper = models.ForeignKey(Paper, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

    class Meta:
        verbose_name = '单选题选项'
        verbose_name_plural = verbose_name

class MC_choice(models.Model):
    choice_symbol = models.CharField('选项符号', max_length=1, choices=SYMBOLS)
    choice_text = models.CharField('选项内容', max_length=200)
    question = models.ForeignKey(MC_question, on_delete=models.CASCADE)
    paper = models.ForeignKey(Paper, on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

    class Meta:
        verbose_name = '多选题选项'
        verbose_name_plural = verbose_name

class Score(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    paper_id = models.ForeignKey(Paper, on_delete=models.CASCADE)
    score = models.DecimalField('分数', max_digits=4,decimal_places=1)
    answer = models.CharField('答题卡', max_length=3072)
    time = models.TimeField('答题计时')

    def __str__(self):
        return '{}-{}'.format(self.paper_id,self.user_id)

    class Meta:
        verbose_name = '成绩'
        verbose_name_plural = verbose_name
        ordering = ['paper_id', '-score']

class File(models.Model):
    file = models.FileField("上传试卷", upload_to=settings.FILE_ROOT)
    name = models.CharField("试卷名称", max_length=200)
    time = models.TimeField("限时")

    class Meta:
        db_table = 'test_file'
        verbose_name = "文件"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name
    

testsystem/forms.py
from django import forms


class UserForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=128)
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    username = forms.CharField(label="姓名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    idcard = forms.CharField(label="学号", max_length=12, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="确认密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别', choices=gender)

testsystem/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Paper,Score
import hashlib
from . import models
from . import forms
from itertools import chain
import json
from django.http import FileResponse

# Create your views here.
def index(request):
    if not request.session.get('is_login', None):#未登录则限制访问
        return redirect('/login/')
    paper_list = Paper.objects.order_by('-id')
    paper_count = Paper.objects.all().count()
    score_list = Score.objects.filter(user_id=request.session['user_id'])
    paper_finish = Score.objects.filter(user_id=request.session['user_id']).values_list('paper_id__paper_text','paper_id__id','paper_id__pub_date')
    paper_nofinish = []
    for i in paper_list:
        flag = False
        for j in paper_finish:
            if i.id == j[1]:
                flag = True
        if not flag:
            paper_nofinish.append(i)
    return render(request, 'testsystem/index.html',{'paper_nofinish':paper_nofinish,'paper_count':paper_count,'score_list': score_list})

def paper(request, paper_id):
    paper = get_object_or_404(Paper, pk=paper_id)
    sc_value_list = [i.value for i in paper.sc_question_set.all()]
    sc_value = value_list_sum(sc_value_list)
    mc_value_list = [i.value for i in paper.mc_question_set.all()]
    mc_value = value_list_sum(mc_value_list)
    blank_value_list = [i.value for i in paper.blank_question_set.all()]
    blank_value = value_list_sum(blank_value_list)
    if models.Score.objects.filter(user_id=request.session['user_id'], paper_id=paper.id):
        passed = True
        answer = models.Score.objects.get(user_id=request.session['user_id'], paper_id=paper.id).answer
        answer_timing = str(models.Score.objects.get(user_id=request.session['user_id'], paper_id=paper.id).time)
        score = models.Score.objects.get(user_id=request.session['user_id'], paper_id=paper.id).score
        return render(request, 'testsystem/paper.html', locals())
    else:
        return render(request, 'testsystem/paper.html', locals())

def login(request):
    if request.session.get('is_login', None):  # 不允许重复登录
        return redirect('/index/')
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        idcard = request.POST.get('idcard')
        message = '请检查填写的内容！'
        if username.strip() and password and idcard:  # 确保用户名和密码都不为空
            # 用户名字符合法性验证
            # 更多的其它验证.....
            try:
                user = models.User.objects.get(idcard=idcard)
            except:
                message = '用户不存在！'
                return render(request, 'testsystem/login.html', {'message': message})
            if user.password == hash_code(password) and username == user.name:
                request.session['is_login'] = True
                request.session['user_id'] = user.id
                request.session['user_name'] = username
                request.session['user_idcard'] = user.idcard
                print(username,idcard, password)
                return redirect('/index/')
            else:
                message = '用户名或密码不正确！'
                return render(request, 'testsystem/login.html', {'message': message})
        else:
            return render(request, 'testsystem/login.html', {'message': message})
    return render(request, 'testsystem/login.html')

def register(request):
    if request.session.get('is_login', None):
        return redirect('/index/')

    if request.method == 'POST':
        register_form = forms.RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():
            username = register_form.cleaned_data.get('username')
            idcard = register_form.cleaned_data.get('idcard')
            password1 = register_form.cleaned_data.get('password1')
            password2 = register_form.cleaned_data.get('password2')
            email = register_form.cleaned_data.get('email')
            sex = register_form.cleaned_data.get('sex')

            if password1 != password2:
                message = '两次输入的密码不同！'
                return render(request, 'testsystem/register.html', locals())
            else:
                same_name_user = models.User.objects.filter(idcard=idcard)
                if same_name_user:
                    message = '学号已经存在'
                    return render(request, 'testsystem/register.html', locals())
                same_email_user = models.User.objects.filter(email=email)
                if same_email_user:
                    message = '该邮箱已经被注册了！'
                    return render(request, 'testsystem/register.html', locals())

                new_user = models.User()
                new_user.name = username
                new_user.idcard = idcard
                new_user.password = hash_code(password1)
                new_user.email = email
                new_user.sex = sex
                new_user.save()

                return redirect('/login/')
        else:
            return render(request, 'testsystem/register.html', locals())
    register_form = forms.RegisterForm()
    return render(request, 'testsystem/register.html', locals())
    
def logout(request):
    if not request.session.get('is_login', None):
        # 如果本来就未登录，也就没有登出一说
        return redirect("/login/")
    request.session.flush()
    return redirect("/login/")

def forgetpwd(request):
    if request.method == "POST":
        idcard = request.POST.get('idcard')
        pwd = request.POST.get('pwd')
        newpwd = request.POST.get('newpwd1')
        newpwd2 = request.POST.get('newpwd2')
        message = '请检查填写的内容！'
        if pwd and idcard:  # 确保学号和旧密码都不为空
            # 用户名字符合法性验证
            # 更多的其它验证.....
            try:
                user = models.User.objects.get(idcard=idcard)
            except:
                message = '用户不存在！'
                return render(request, 'testsystem/forgetpwd.html', {'message': message})
            if user.password == hash_code(pwd):
                if newpwd == newpwd2:
                    user.password = hash_code(newpwd)
                    user.save()
                    print('aaaa')
                    return redirect('/login/')
                else:
                    message = '两次输入的密码不同！'
                    return render(request, 'testsystem/forgetpwd.html', {'message': message})    
            else:
                message = '密码不正确！'
                return render(request, 'testsystem/forgetpwd.html', {'message': message})
        else:
            return render(request, 'testsystem/forgetpwd.html', {'message': message})
    return render(request, 'testsystem/forgetpwd.html')

def hash_code(s,salt='login'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())
    return h.hexdigest()

def value_list_sum(value_list):
    value_sum = 0
    for value in value_list:
        value_sum += value
    return int(value_sum) if '.0' in str(value_sum) else value_sum

def cal_score(request, paper_id):
    paper = get_object_or_404(Paper, pk=paper_id)
    score = 0
    postdata = {}
    for i in paper.sc_question_set.all():
        postdata[str(i)] = request.POST.get(str(i))
        if i.SC_solution == request.POST.get(str(i)):
            score += i.value
    for i in paper.mc_question_set.all():
        solv_list = list(i.MC_solution)
        post_list = request.POST.getlist(str(i))
        postdata[str(i)] = post_list
        if solv_list == post_list:
            score += i.value
    for i in paper.blank_question_set.all():
        postdata[str(i)] = request.POST.get(str(i))
        if i.blank_solution == request.POST.get(str(i)):
            score += i.value
    new_score = Score()
    new_score.paper_id_id = paper.id
    new_score.user_id_id = request.session['user_id']
    new_score.score = score
    new_score.answer = json.dumps(postdata, separators=(',',':'))
    new_score.time = request.POST.get('timing').replace('PT','').replace('H',':').replace('M',':').replace('S','')
    new_score.save()
    return redirect('/{}/'.format(paper_id))

def download(request):
  file=open('testsystem/download/STU-question_bank_template.xlsx','rb')
  response =FileResponse(file)
  response['Content-Type']='application/octet-stream'
  response['Content-Disposition']='attachment;filename="STU-question_bank_template.xlsx"'
  return response

testsystem/templates/testsystem/paper.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="content-type" content="text/html;charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<title>{{paper.paper_text}}</title>
<link href="{% static '/test/css/main.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static '/test/css/iconfont.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static '/test/css/test.css' %}" rel="stylesheet" type="text/css" />
{% if passed %}
	<script type="text/javascript">
		obj = JSON.parse('{{answer|safe}}')
	</script>
{% endif %}
<style>
.hasBeenAnswer {
	background: #5d9cec;
	color:#fff;
}
</style>

</head>

<body>
	<div class="main">
		<!--nr start-->
		<div class="test_main">
			<div class="nr_left">
				<div class="test">
					<form action="/{{paper.id}}/cal/" method="post">
					{% csrf_token %}
						<div class="test_title">
							<p class="test_time">
								<i class="icon iconfont"></i>
								{% if passed %}
									<b>{{answer_timing}}</b>
								{% else %}
									<b class="alt-1">{{paper.time}}</b>
								{% endif %}
							</p>
							{% if passed %}
								<font><a href="/index/">返回</a></font>
							{% else %}
								<font><input type="submit" name="test_jiaojuan" value="交卷"></font>
							{% endif %}
						</div>
						<div class="test_content">
							<div class="test_content_title">
								<h2>单选题</h2>
								<p>
									<span>共</span><i class="content_lit">{{paper.sc_question_set.all.count}}</i><span>题，</span><span>合计</span><i class="content_fs">{{sc_value}}</i><span>分</span>
								</p>
							</div>
						</div>
						<div class="test_content_nr">
							<ul>
								{% if paper.sc_question_set %}
									{% for sc_question in paper.sc_question_set.all %}
										<li id="sc_question{{forloop.counter}}">
											<div class="test_content_nr_tt">
												<i>{{forloop.counter}}</i><span>({{sc_question.value}}分)</span><font>{{sc_question.SC_text}}</font><b class="icon iconfont"></b>
											</div>

											<div class="test_content_nr_main">
												<ul>
													{% if sc_question.sc_choice_set %}
														{% for sc_choice in sc_question.sc_choice_set.all %}
															<li class="option">
																
																	<input type="radio" class="radioOrCheck" name="sc_question{{sc_question.id}}"
																		id="sc_choice{{sc_choice.id}}" value="{{sc_choice.choice_symbol}}"
																	/>
																
																<label for="sc_choice{{sc_choice.id}}">
																	{{sc_choice.choice_symbol}}.
																	<p class="ue" style="display: inline;">{{sc_choice.choice_text}}</p>
																</label>

															</li>
														{% endfor %}
													{% endif %}													
												</ul>
											</div>
										{% if passed %}
											<script>
												if(obj.sc_question{{sc_question.id}} == '{{sc_question.SC_solution}}'){
													document.write("<div class=\"answer_right\">答案：\
													<span style='font-size: 18px;margin-right: 12px;'>{{sc_question.SC_solution}}</span>\
													<span style='font-size: 12px;'>你答对了</span></div>")
												}
												else{
													document.write("<div class=\"answer_false\">答案：\
													<span style='font-size: 18px;margin-right: 12px;'>{{sc_question.SC_solution}}</span>\
													<span style='font-size: 12px;'>你答错了</span></div>")
												}
												
												var div1 = document.querySelectorAll('input[name="sc_question{{sc_question.id}}"]');
												for(var i=0; i<div1.length; i++){
													if(div1[i].value==obj.sc_question{{sc_question.id}}){
														div1[i].setAttribute('checked','true');
													}
												}
											</script>
										{% endif %}
										</li>
									{% endfor %}
								{% else %}
									<p>No question</p>
								{% endif %}
							</ul>
						</div>                                
					
						<div class="test_content">
							<div class="test_content_title">
								<h2>多选题</h2>
								<p>
									<span>共</span><i class="content_lit">{{paper.mc_question_set.all.count}}</i><span>题，</span><span>合计</span><i class="content_fs">{{mc_value}}</i><span>分</span>
								</p>
							</div>
						</div>
						<div class="test_content_nr">
							<ul>
								{% if paper.mc_question_set %}
									{% for mc_question in paper.mc_question_set.all%}
										<li id="mc_question{{forloop.counter}}">
											<div class="test_content_nr_tt">
												<i>{{forloop.counter}}</i><span>({{mc_question.value}}分)</span><font>{{mc_question.MC_text}}</font><b class="icon iconfont"></b>
											</div>

											<div class="test_content_nr_main">
												<ul>
													{% if mc_question.mc_choice_set %}
														{% for mc_choice in mc_question.mc_choice_set.all%}
															<li class="option">
																
																	<input type="checkbox" class="radioOrCheck" name="mc_question{{mc_question.id}}"
																		id="mc_choice{{mc_choice.id}}" value="{{mc_choice.choice_symbol}}"
																	/>
																
																<label for="mc_choice{{mc_choice.id}}">
																	{{mc_choice.choice_symbol}}.
																	<p class="ue" style="display: inline;">{{mc_choice.choice_text}}</p>
																</label>
															</li>
														{% endfor %}
													{% endif %}
																										
												</ul>
											</div>
										{% if passed %}
											<script>
												if(obj.mc_question{{mc_question.id}}.join('') == '{{mc_question.MC_solution}}'){
													document.write("<div class=\"answer_right\">答案：\
													<span style='font-size: 18px;margin-right: 12px;'>{{mc_question.MC_solution}}</span>\
													<span style='font-size: 12px;'>你答对了</span></div>")
												}
												else{
													document.write("<div class=\"answer_false\">答案：\
													<span style='font-size: 18px;margin-right: 12px;'>{{mc_question.MC_solution}}</span>\
													<span style='font-size: 12px;'>你答错了</span></div>")
												}
												var lst = obj.mc_question{{mc_question.id}};
												var div1 = document.querySelectorAll('input[name="mc_question{{mc_question.id}}"]');
												for(var i=0; i<div1.length; i++){
													for(var j=0; j<lst.length; j++){
														if(div1[i].value == lst[j]){
															div1[i].setAttribute('checked','true');
														}
													}
												}
											</script>
										{% endif %}
										</li>
									{% endfor %}
								{% else %}
									<p>No question</p>
								{% endif %}
							</ul>
						</div>

						<div class="test_content">
							<div class="test_content_title">
								<h2>填空题</h2>
								<p>
									<span>共</span><i class="content_lit">{{paper.blank_question_set.all.count}}</i><span>题，</span><span>合计</span><i class="content_fs">{{blank_value}}</i><span>分</span>
								</p>
							</div>
						</div>
						<div class="test_content_nr">
							<ul>
								{% if paper.blank_question_set %}
									{% for blank_question in paper.blank_question_set.all%}
										<li id="blank_question{{forloop.counter}}">
											<div class="test_content_nr_tt">
												<i>{{forloop.counter}}</i><span>({{blank_question.value}}分)</span><font>{{blank_question.blank_text}}</font><b class="icon iconfont"></b>
											</div>

											<div class="test_content_nr_main">
												<input class="blank" type="text" name="blank_question{{blank_question.id}}"
													id="blank_question{{forloop.counter}}" style="width:700px; height:30px; padding-left:5px;"
												/>
											</div>
										{% if passed %}
											<script>
												if(obj.blank_question{{blank_question.id}} == '{{blank_question.blank_solution}}'){
													document.write("<div class=\"answer_right\">答案：\
													<span style='font-size: 18px;margin-right: 12px;'>{{blank_question.blank_solution}}</span>\
													<span style='font-size: 12px;'>你答对了</span></div>")
												}
												else{
													document.write("<div class=\"answer_false\">答案：\
													<span style='font-size: 18px;margin-right: 12px;'>{{blank_question.blank_solution}}</span>\
													<span style='font-size: 12px;'>你答错了</span></div>")
												}
												debugger;
												document.getElementsByName("blank_question{{blank_question.id}}")[0].value = obj.blank_question{{blank_question.id}};
												document.getElementsByName("blank_question{{blank_question.id}}")[0].disabled = "disabled";
											</script>
										{% endif %}
										</li>
									{% endfor %}
								{% else %}
									<p>No question</p>
								{% endif %}
							</ul>
						</div>
						
					</form>
				</div>

			</div>
			<div class="nr_right">
				<div class="nr_rt_main">
					<div class="rt_nr1">
						<div class="rt_nr1_title">
							<h1>
								<i class="icon iconfont"></i>答题卡
							</h1>
							<p class="test_time">
								<i class="icon iconfont"></i>
								{% if passed %}
									<b>{{answer_timing}}</b>
								{% else %}
									<b class="alt-1">{{paper.time}}</b>
								{% endif %}
							</p>
						</div>
						
						<div class="rt_content">
							<div class="rt_content_tt">
								<h2>单选题</h2>
								<p>
									<span>共</span><i class="content_lit">{{paper.sc_question_set.all.count}}</i><span>题</span>
								</p>
							</div>
							<div class="rt_content_nr answerSheet">
								<ul>
									{% if paper.sc_question_set %}
										{% for sc_question in paper.sc_question_set.all %}
											<li><a href="#sc_question{{forloop.counter}}">{{forloop.counter}}</a></li>
										{% endfor %}
									{% endif %}
																			
								</ul>
							</div>
						</div>
					
						<div class="rt_content">
							<div class="rt_content_tt">
								<h2>多选题</h2>
								<p>
									<span>共</span><i class="content_lit">{{paper.mc_question_set.all.count}}</i><span>题</span>
								</p>
							</div>
							<div class="rt_content_nr answerSheet">
								<ul>
									{% if paper.mc_question_set %}
										{% for mc_question in paper.mc_question_set.all %}
											<li><a href="#mc_question{{forloop.counter}}">{{forloop.counter}}</a></li>
										{% endfor %}
									{% endif %}

								</ul>
							</div>
						</div>

						<div class="rt_content">
							<div class="rt_content_tt">
								<h2>填空题</h2>
								<p>
									<span>共</span><i class="content_lit">{{paper.blank_question_set.all.count}}</i><span>题</span>
								</p>
							</div>
							<div class="rt_content_nr answerSheet">
								<ul>
									{% if paper.blank_question_set %}
										{% for blank_question in paper.blank_question_set.all %}
											<li><a href="#blank_question{{forloop.counter}}">{{forloop.counter}}</a></li>
										{% endfor %}
									{% endif %}

								</ul>
							</div>
						</div>
						{% if passed %}
							<div class="rt_content">
								<div class="ibox-content">
									<h2>成绩：{{score}}</h2>
								</div>
							</div>
						{% endif %}

					</div>
				</div>
			</div>
		</div>
		<!--nr end-->
		<div class="foot"></div>
	</div>

	<script src="{% static '/test/js/jquery-1.11.3.min.js' %}"></script>
	<script src="{% static 'jquery.easy-pie-chart.js' %}"></script>
	<!--时间js-->
	<script src="{% static 'test/js/jquery.countdown.js' %}"></script>
	<script>
		window.jQuery(function($) {
			"use strict";
			
			$('time').countDown({
				with_separators : false
			});
			$('.alt-1').countDown({
				css_class : 'countdown-alt-1'
			});
			$('.alt-2').countDown({
				css_class : 'countdown-alt-2'
			});

		});

		$(function() {
			$('li.option label').click(function() {
			debugger;
				var examId = $(this).closest('.test_content_nr_main').closest('li').attr('id'); // 得到题目ID
				var cardLi = $('a[href=#' + examId + ']'); // 根据题目ID找到对应答题卡
				// 设置已答题
				if(!cardLi.hasClass('hasBeenAnswer')){
					cardLi.addClass('hasBeenAnswer');
				}
				
			});
		});

		$(function() {
			$('input.blank').bind("input propertychange change",function() {
			debugger;
				var examId = $(this).closest('li').attr('id'); // 得到题目ID
				var cardLi = $('a[href=#' + examId + ']'); // 根据题目ID找到对应答题卡
				// 设置已答题
				if(!cardLi.hasClass('hasBeenAnswer')){
					cardLi.addClass('hasBeenAnswer');
				}

			});
		});

		$(function(){
			$('form').submit(function(){
				var timing = $('<input name="timing" type="hidden"/>');
				timing.attr('value', $('time').attr('datetime'));
				$('form').append(timing);
				
			})
		})

	</script>

<div style="text-align:center;">
</div>

</body>

</html>